# -*- coding: utf-8 -*-
"""
Created on Thu May 18 10:01:38 2017

@author: FR015797
Date of last revision: May 18th 2017
"""


#--------------------------------------------------
#           Project packages
#--------------------------------------------------
from Asset import Asset

#--------------------------------------------------
#           Python packages
#--------------------------------------------------
import numpy as np
import pandas as pd
#--------------------------------------------------
#       Start of the proper code
#--------------------------------------------------

class Cash(Asset):   
    """
        represents Cash-like instruments. 
        
        This class inherited from the *Asset* class
        
        :param volume: Time serie of the volume of Equities over time
        :param value: Time serie of the value of the Equity over time
        :param time_horizon: Duration of the simulation
        :param starting_point: Point of time in the simulation when the instrument is emitted
        :param flag: hidden variables equal to 0 by default
        :param return_rate: Time serie of the value of the interest rate of the Equity over time
        :param potential: Time serie of the potential gain & loss on the Equity
        :type volume: DataFrame of Integer
        :type value: DataFrame of Float
        :type time_horizon: Integer
        :type starting_point: Integer
        :type flag: Float
        :type return_rate: DataFrame of Float
        :type potential: DataFrame of Float
        :return: An instance of the Cash class
        :rtype: Cash object
    """     
    def updateValue(self, current_step):
        """
            capitalizes the Equity over a period of time
        """
        self.value.loc[current_step:self.time_horizon, 'Value'] = self.value.loc[current_step, 'Value'] * (1 + self.return_rate.loc[current_step, 'RRate'])
        
    def cashOut(self, current_step):
        """
            cashes out the amount of money generated by the Equity
        """
        output = self.value.loc[current_step, 'Value'] * self.volume.loc[current_step, 'Volume']
        if(current_step < self.time_horizon):
            self.volume.loc[np.arange(current_step+1,self.time_horizon+1), 'Volume'] = 0
#            print("Cash cashout")
        return output    
    
    def getWealth(self, current_step):
        """
            returns the amount of money represented by the Equity at a certain point in time
        """
        return (self.value.loc[current_step, 'Value'] * self.volume.loc[current_step, 'Volume'])

    def update(self, current_step):
        """
            updates the Equity over a period of time
        """
        self.updateValue(current_step)
    
#--------------------------------------------------
#       Start of the testing part of the code
#--------------------------------------------------
#
#def main():
#    cash = Cash(value=1, volume=100, return_rate=0.01, time_horizon=20)
#    for i in range(1,cash.time_horizon+1):
#        cash.update(i)
#    print(cash.value['Value'] * cash.volume['Volume'])

#    print(cash.return_rate)
#    (cash.value['Value']*cash.volume['Volume']).plot()
#    print("--- %s seconds ---" % (time.time() - start_time))
    
#if __name__ == "__main__":
#    main()